language: r

matrix:
  include:
    - dist: xenial
      r: release
    - dist: xenial
      r: devel
    - dist: trusty
      r: release
    - os: osx
      r: release
#    - os: osx
#      r: devel

r_github_packages:
  - r-lib/covr

# execute code coverage, but ignore files that are tested in their own packages
after_success:
  - Rscript -e 'covr::codecov(line_exclusions=list("COrthogonalArray.cpp", "COrthogonalArray.h"))'

cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"

sudo: false
