language: r

# execute code coverage, but ignore files that are tested in their own packages
#  these files from from bertcarnell/oa, bertcarnell/bclib, and bertcarnell/lhslib
matrix:
  include:
    - dist: xenial
      r: release
      after_success: Rscript -e 'covr::codecov(line_exclusions=list("src/COrthogonalArray.cpp", "src/COrthogonalArray.h", "src/CRandom.h", "src/RStandardUniform.h", "src/ak3.cpp", "src/akconst.cpp", "src/akn.cpp", "src/construct.cpp", "src/galdef.h", "src/galois.cpp", "src/geneticLHS.cpp", "src/gfields.cpp", "src/improvedLHS.cpp", "src/matrix.h", "src/maximinLHS.cpp", "src/oa.cpp", "src/oaLHS.cpp", "src/oaLHSUtility.h", "src/optSeededLHS.cpp", "src/optimumLHS.cpp", "src/order.h", "src/primes.cpp", "src/randomLHS.cpp", "src/runif.cpp", "src/runif.h", "src/rutils.cpp", "src/rutils.h", "src/utilityLHS.cpp", "src/utilityLHS.h", "src/xtndeclare.h", "src/xtndispatch.h", "src/xtnset.h"))'
    - dist: xenial
      r: devel
    - dist: bionic
      r: release
    - dist: focal
      r: release
    - os: osx
      r: release

r_github_packages:
  - r-lib/covr

cache: packages
warnings_are_errors: true
r_check_args: "--as-cran"

sudo: false
