comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

codecov:
  token: 5037e846-ad23-45bb-a691-27f5fbcb94e5
