name: docker-builds

on:
  workflow_dispatch:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v4

      - name: R
        uses: r-lib/actions/setup-r@v2

      - name: Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Dependencies and Build the Package
        run: |
          install.packages(c('pkgbuild', 'knitr', 'rmarkdown', 'Rcpp', 'rhub'))
          file_name <- pkgbuild::build("../lhs")
        shell: Rscript {0}

      - name: Pull Docker and Copy in the Package
        shell: bash
        run: |
          docker pull bertcarnell/lhs-debug
          docker run --rm -dit --security-opt seccomp=unconfined --name rdevel bertcarnell/lhs-debug
          docker cp ../lhs_*.tar.gz rdevel:home

      - name: Valgrind
        shell: bash
        run: |
          test=`docker exec rdevel ls \home | grep .tar.gz`
          echo $test
          docker exec rdevel RDvalgrind CMD check --use-valgrind --ignore-vignettes /home/$test

      - name: Address Sanitizers
        shell: bash
        run: |
          test=`docker exec rdevel ls \home | grep .tar.gz`
          echo $test
          docker exec rdevel RDsan CMD check --ignore-vignettes /home/$test

      - name: Clang Address Sanitizers
        shell: bash
        run: |
          test=`docker exec rdevel ls \home | grep .tar.gz`
          echo $test
          docker exec rdevel RDcsan CMD check --ignore-vignettes /home/$test

      - name: Clean up
        shell: bash
        run: |
          docker stop rdevel # also removes the docker since we ran it with --rm
