# Workflow derived from https://github.com/r-lib/actions/tree/master/examples

on:
  push:
    tags: ['*']
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rmarkdown, knitr, pkgdown

      - name: build site
        shell: bash
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs/*.*
          git commit -m 'Automatic build of lhs website'
          git push
