name: Rev-Dep-Check

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Pull Docker
        shell: bash
        # the working director is /home/runner/work/lhs/lhs
        run: |
          docker pull bertcarnell/lhs_revdep

      - name: Run the reverse dependencies
        shell: bash
        # the working director is /home/runner/work/lhs/lhs
        run: |
          chmod -R a+rw /home/runner/work/lhs
          docker run -dti --rm --security-opt seccomp=unconfined -v /home/runner/work/lhs:/home/docker -w /home/docker -u docker --name lhs_revdep_check bertcarnell/lhs_revdep
          docker exec lhs_revdep_check Rscript /home/docker/lhs/etc/lhs_rev_dep_check.R

      - name: Clean up
        shell: bash
        run: |
          docker stop lhs_revdep_check # also removes the docker since we ran it with --rm
