name: Rev-Dep-Check

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {which_type: 'Depends'}
          #- {which_type: 'Imports'}
          #- {which_type: 'Suggests'}
    
    name: Rev-Dep-Check ${{ matrix.config.which_type }}

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Pull Docker
        shell: bash
        # the working director is /home/runner/work/lhs/lhs
        run: |
          docker pull bertcarnell/lhs_revdep

      - name: Run the reverse dependencies
        shell: bash
        # the working director is /home/runner/work/lhs/lhs
        run: |
          chmod -R a+rw /home/runner/work/lhs
          docker run -dti --rm --security-opt seccomp=unconfined -v /home/runner/work/lhs:/home/docker -w /home/docker -u docker --name lhs_revdep_check bertcarnell/lhs_revdep
          docker exec lhs_revdep_check Rscript /home/docker/lhs/etc/lhs_rev_dep_check.R "lhs" "1.1.3" ${{ matrix.config.which_type }}
          
      - name:  Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: etc/revdep_README.md

      - name: Commit Reverse Dependency Results
        shell: bash
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull
          git add etc/revdep_README_${{ matrix.config.which_type }}.md
          git commit -m 'Automatic Reverse Dependency Check Results for ${{ matrix.config.which_type }}'
          git push

      - name: Clean up
        shell: bash
        run: |
          docker stop lhs_revdep_check # also removes the docker since we ran it with --rm
