name: Rhub-Checks

on: workflow_dispatch

jobs:
  Rhub-checks-job:
    runs-on: windows-latest

    name: ${{ matrix.config.cmd }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {cmd: check_with_valgrind}
          - {cmd: check_with_sanitizers}
          - {cmd: check_for_cran}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: R
        uses: r-lib/actions/setup-r@v2

      - name: Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Dependencies
        run: |
          install.packages(c('pkgbuild', 'knitr', 'rmarkdown', 'Rcpp', 'rhub'))
        shell: Rscript {0}

      - name: Build Package and Run through Rhub
        run: |
          file_name <- pkgbuild::build("../lhs")
          rhub::validate_email(email = "${{ secrets.RHUB_EMAIL }}", token = "${{ secrets.RHUB_EMAIL_TOKEN }}")
          rhub::${{ matrix.config.cmd }}(path=file_name)
        shell: Rscript {0}
